apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: dev-


patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "50m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "32Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "250m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "128Mi"
  target:
    kind: Deployment
    name: es-meili-growi-bridge

configMapGenerator:
- behavior: merge
  literals:
  - LOG_LEVEL=debug
  name: es-meili-growi-bridge-config
labels:
- includeSelectors: true
  pairs:
    environment: dev
