apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: prod-


patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: MEILISEARCH_URL
          valueFrom:
            secretKeyRef:
              name: meilisearch-credentials
              key: url
        - name: MEILISEARCH_API_KEY
          valueFrom:
            secretKeyRef:
              name: meilisearch-credentials
              key: api-key
  target:
    kind: Deployment
    name: es-meili-growi-bridge
labels:
- includeSelectors: true
  pairs:
    environment: prod
